language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - sudo apt-get install -y curl
script:
  - make all
  - cd step_1 && make all
  - cd ../step_2 && make all
  - cd ../step_3 && make all
  - cd ../step_4 && make all
  - cd ../step_5 && make all && make figs/all.png
