language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - sudo apt-get install -y curl
script:
  - make test
  - cd step_1 && make test
  - cd step_2 && make test
  - cd step_3 && make test
  - cd step_4 && make test
  - cd step_5 && make test
